dist: xenial

language: c

compiler:
    - gcc

env:
    - targets="K2P K2P_nano"

addons:
    apt:
      packages: [ fakeroot, p7zip-full, autoconf, automake, bison, build-essential,
        flex, gawk, gettext, gperf, libtool, pkg-config, zlib1g-dev, libgmp3-dev,
        libmpc-dev, libmpfr-dev, texinfo, python-docutils, libncurses5-dev, curl,
        autopoint, libltdl-dev, cmake ]

before_script:
    - cd /opt && mkdir images && git clone --depth=1 https://github.com/hanwckf/rt-n56u.git
    - cd rt-n56u && rm -rf toolchain-mipsel/
    - git clone --depth=1 https://github.com/hanwckf/padavan-toolchain.git toolchain-mipsel && chmod u+x ./toolchain-mipsel/toolchain-3.4.x/bin/*
    - ls -Alh /opt/rt-n56u && cd /opt/rt-n56u/trunk/

script:
    - for m in $targets; do fakeroot ./build_firmware_nohup $m && cp -f images/*.trx /opt/images/$m.trx; ./clear_tree_simple >/dev/null 2>&1; done

after_script:
    - GIT_VERSION=`git rev-parse --short=7 HEAD 2>/dev/null` && [ -n "$GIT_VERSION" ] && image_name=images_mt7621_$GIT_VERSION || image_name=images_mt7621
    - cd /opt/images && md5sum *.trx |tee md5sum.txt && 7z a -mx=9 ${image_name}.7z ./*
    - echo $(curl -# --upload-file ./${image_name}.7z https://transfer.sh/${image_name}.7z)

git:
    depth: 3
